// SERVER-ONLY (see ./client.ts). Persists what each model forecast, so its skill can be measured.
import type {
  ForecastResponse,
  LevelId,
  ModelId,
  SnowSource,
} from '../../types/forecast.js';
import { round } from '../forecast/math.js';
import { upsertRows, warnDatabase, type NieveDatabase } from './client.js';
import { resortLocalDate } from './dates.js';

export const FORECAST_SNAPSHOTS_TABLE = 'forecast_snapshots';
export const FORECAST_SNAPSHOTS_CONFLICT = 'model,level,target_date,issued_date';

/** A row of `nieve.forecast_snapshots` (`lead_days` is generated by the database). */
export interface ForecastSnapshotRow {
  model: ModelId;
  level: LevelId;
  target_date: string;
  issued_date: string;
  snowfall_cm: number;
  snow_source: SnowSource;
  fetched_at: string;
}

function primaryKey(row: ForecastSnapshotRow): string {
  return `${row.model}|${row.level}|${row.target_date}|${row.issued_date}`;
}

/**
 * One row per model, level and forecast day that has a model value. `issued_date` is the resort's
 * local date of the forecast update, so later fetches on the same day overwrite earlier ones.
 */
export function rowsFromForecast(response: ForecastResponse): ForecastSnapshotRow[] {
  const fetchedAt = response.resort.updatedAt;
  const issuedDate = resortLocalDate(fetchedAt);
  if (!issuedDate) return [];

  const rows = new Map<string, ForecastSnapshotRow>();
  response.levels.forEach((level) => {
    level.daily.forEach((day) => {
      day.models.forEach((value) => {
        const snowfall = value.snowfallCm;
        if (snowfall === null || !Number.isFinite(snowfall) || snowfall < 0) return;
        const row: ForecastSnapshotRow = {
          model: value.model,
          level: level.level.id,
          target_date: day.date,
          issued_date: issuedDate,
          snowfall_cm: round(snowfall) ?? 0,
          snow_source: value.source,
          fetched_at: fetchedAt,
        };
        rows.set(primaryKey(row), row);
      });
    });
  });
  return [...rows.values()];
}

/** Best effort: returns false (and logs) on any failure or when there is no database. */
export async function saveForecastSnapshots(
  client: NieveDatabase | null,
  response: ForecastResponse,
): Promise<boolean> {
  if (!client) return false;
  try {
    return await upsertRows(
      client,
      FORECAST_SNAPSHOTS_TABLE,
      rowsFromForecast(response),
      FORECAST_SNAPSHOTS_CONFLICT,
    );
  } catch (error) {
    warnDatabase(`save ${FORECAST_SNAPSHOTS_TABLE}`, error);
    return false;
  }
}
